# This file needs to be modified in production.
services:
  web:
    build: .
    container_name: ankard_web
    env_file: .env
    volumes:
      - .:/app
    expose:
      - "8000"
    # Development only: enables hot-reload on code changes using Gunicorn. Remove '--reload' in production.
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    restart: unless-stopped
    networks:
      - ankard_net

  nginx:
    image: nginx:1.28.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - ankard_net

# Explicitly define networks for clarity, isolation, and future scalability.
# - Makes service-to-service connections clearer
# - Enables better control over internal communication
# - Avoids conflicts in multi-file or multi-environment setups
networks:
  ankard_net:
    driver: bridge
